# Generated by Django 6.0.3 on 2026-03-25 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('framework', models.CharField(choices=[('fastapi', 'FastAPI'), ('flask', 'Flask'), ('django', 'Django'), ('express', 'Express'), ('react', 'React'), ('docker', 'Docker'), ('go', 'Go'), ('rust', 'Rust')], max_length=30)),
                ('source_type', models.CharField(choices=[('github', 'GitHub Repo'), ('docker_image', 'Docker Image'), ('manual_upload', 'Manual Upload')], max_length=30)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('build_command', models.CharField(blank=True, max_length=255, null=True)),
                ('start_command', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField()),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('https_enabled', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
