# Generated by Django 6.0.3 on 2026-03-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='port',
        ),
    ]
