# Generated by Django 6.0.3 on 2026-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_manager', '0003_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='port',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
