# Generated by Django 6.0.3 on 2026-03-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_manager', '0004_app_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='container_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
